namespace ECommerceAPI.Infrastructure.Operations;

public class NameOperation
{
    public static string CharacterRegulatory(string name)

        => name.Replace("\"", "")
            .Replace("!", "")
            .Replace("'", "")
            .Replace("^", "")
            .Replace("+", "")
            .Replace("%", "")
            .Replace("&", "")
            .Replace("/", "")
            .Replace("(", "")
            .Replace(")", "")
            .Replace(" ", "")
            .Replace("=", "")
            .Replace("?", "")
            .Replace("_", "-")
            .Replace("£", "")
            .Replace(">", "")
            .Replace("<", "")
            .Replace("#", "")
            .Replace("$", "")
            .Replace("½", "")
            .Replace("§", "")
            .Replace("|", "")
            .Replace(",", "")
            .Replace(";", "")
            .Replace("`", "")
            .Replace(".", "-")
            .Replace(":", "")
            .Replace("@", "")
            .Replace("∑", "")
            .Replace("€", "")
            .Replace("®", "")
            .Replace("₺", "")
            .Replace("¥", "")
            .Replace("¨", "")
            .Replace("π", "")
            .Replace("~", "")
            .Replace("æ", "")
            .Replace("´", "")
            .Replace("¬", "")
            .Replace("∆", "")
            .Replace("^", "")
            .Replace("ƒ", "")
            .Replace("∂", "")
            .Replace("ß", "")
            .Replace("≈", "")
            .Replace("√", "")
            .Replace("∫", "")
            .Replace("≤", "")
            .Replace("≥", "")
            .Replace("÷", "")
            .Replace("µ", "")
            .Replace("ğ", "g")
            .Replace("Ğ", "g")
            .Replace("Ü", "u")
            .Replace("ü", "u")
            .Replace("Ş", "s")
            .Replace("ş", "s")
            .Replace("İ", "i")
            .Replace("ı", "i")
            .Replace("Ö", "o")
            .Replace("ö", "o")
            .Replace("Ç", "c")
            .Replace("ç", "c");
}